# encoding: UTF-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)

Breed.delete_all
Breed.create(:name => "Pointer", :fci_number => 1)
Breed.create(:name => "English Setter", :fci_number => 2)
Breed.create(:name => "Kerry Blue Terrier", :fci_number => 3)
Breed.create(:name => "Cairn Terrier", :fci_number => 4)
Breed.create(:name => "English Cocker Spaniel", :fci_number => 5)
Breed.create(:name => "Gordon Setter", :fci_number => 6)
Breed.create(:name => "Airedale Terrier", :fci_number => 7)
Breed.create(:name => "Australian Terrier", :fci_number => 8)
Breed.create(:name => "Bedlington Terrier", :fci_number => 9)
Breed.create(:name => "Border Terrier", :fci_number => 10)
Breed.create(:name => "Bull Terrier", :fci_number => 11)
Breed.create(:name => "Fox Terrier (Smooth)", :fci_number => 12)
Breed.create(:name => "English Toy Terrier (Black & Tan)", :fci_number => 13)
Breed.create(:name => "Swedish Vallhund", :fci_number => 14)
Breed.create(:name => "Belgian Shepherd (Tervuren)", :fci_number => 15)
Breed.create(:name => "Belgian Shepherd Dog (Groenendael)", :fci_number => 15)
Breed.create(:name => "Belgian Shepherd Dog (Laekenois)", :fci_number => 15)
Breed.create(:name => "Belgian Shepherd Dog (Malinois)", :fci_number => 15)
Breed.create(:name => "Cão de Castro Laboreiro", :fci_number => 15)
Breed.create(:name => "Old English Sheepdog", :fci_number => 16)
Breed.create(:name => "Griffon Nivernais", :fci_number => 17)
Breed.create(:name => "Briquet Griffon Vendéen", :fci_number => 19)
Breed.create(:name => "Ariegeois", :fci_number => 20)
Breed.create(:name => "Gascon Saintongeois", :fci_number => 21)
Breed.create(:name => "Grand Bleu de Gascogne", :fci_number => 22)
Breed.create(:name => "Billy", :fci_number => 25)
Breed.create(:name => "Artois Hound", :fci_number => 28)
Breed.create(:name => "Porcelaine", :fci_number => 30)
Breed.create(:name => "Petit Bleu de Gascogne", :fci_number => 31)
Breed.create(:name => "Anglo-Français de Petite Vénerie", :fci_number => 32)
Breed.create(:name => "Griffon Bleu de Gascogne", :fci_number => 32)
Breed.create(:name => "Basset Artésien Normand", :fci_number => 34)
Breed.create(:name => "Basset Bleu de Gascogne", :fci_number => 35)
Breed.create(:name => "Portuguese Water Dog", :fci_number => 37)
Breed.create(:name => "Cardigan Welsh Corgi", :fci_number => 38)
Breed.create(:name => "Pembroke Welsh Corgi", :fci_number => 39)
Breed.create(:name => "Soft-Coated Wheaten Terrier", :fci_number => 40)
Breed.create(:name => "Šarplaninac", :fci_number => 41)
Breed.create(:name => "Jämthund", :fci_number => 42)
Breed.create(:name => "Basenji", :fci_number => 43)
Breed.create(:name => "Beauceron", :fci_number => 44)
Breed.create(:name => "Bernese Mountain Dog", :fci_number => 45)
Breed.create(:name => "Entlebucher Mountain Dog", :fci_number => 47)
Breed.create(:name => "Karelian Bear Dog", :fci_number => 48)
Breed.create(:name => "Finnish Spitz", :fci_number => 49)
Breed.create(:name => "Newfoundland", :fci_number => 50)
Breed.create(:name => "Finnish Hound", :fci_number => 51)
Breed.create(:name => "Polish Hound", :fci_number => 52)
Breed.create(:name => "Komondor", :fci_number => 53)
Breed.create(:name => "Kuvasz", :fci_number => 54)
Breed.create(:name => "Puli", :fci_number => 55)
Breed.create(:name => "Pumi", :fci_number => 56)
Breed.create(:name => "Vizsla", :fci_number => 57)
Breed.create(:name => "Greater Swiss Mountain Dog", :fci_number => 58)
Breed.create(:name => "Schweizer Laufhund", :fci_number => 59)
Breed.create(:name => "Schweizerischer Niederlaufhund", :fci_number => 60)
Breed.create(:name => "St. Bernard", :fci_number => 61)
Breed.create(:name => "Styrian Coarse-haired Hound", :fci_number => 62)
Breed.create(:name => "Austrian Black and Tan Hound", :fci_number => 63)
Breed.create(:name => "Austrian Pinscher", :fci_number => 64)
Breed.create(:name => "Maltese", :fci_number => 65)
Breed.create(:name => "Griffon Fauve de Bretagne", :fci_number => 66)
Breed.create(:name => "Petit Basset Griffon Vendéen", :fci_number => 67)
Breed.create(:name => "Tyrolean Hound", :fci_number => 68)
Breed.create(:name => "Lakeland Terrier", :fci_number => 70)
Breed.create(:name => "Manchester Terrier", :fci_number => 71)
Breed.create(:name => "Norwich Terrier", :fci_number => 72)
Breed.create(:name => "Skye Terrier", :fci_number => 72)
Breed.create(:name => "Scottish Terrier", :fci_number => 73)
Breed.create(:name => "Sealyham Terrier", :fci_number => 74)
Breed.create(:name => "Staffordshire Bull Terrier", :fci_number => 76)
Breed.create(:name => "Papillon", :fci_number => 77)
Breed.create(:name => "Welsh Terrier", :fci_number => 78)
Breed.create(:name => "Schipperke", :fci_number => 83)
Breed.create(:name => "Bloodhound", :fci_number => 84)
Breed.create(:name => "West Highland White Terrier", :fci_number => 85)
Breed.create(:name => "Yorkshire Terrier", :fci_number => 86)
Breed.create(:name => "Catalan Sheepdog", :fci_number => 87)
Breed.create(:name => "Shetland Sheepdog", :fci_number => 88)
Breed.create(:name => "Ibizan Hound", :fci_number => 89)
Breed.create(:name => "Spanish Mastiff", :fci_number => 91)
Breed.create(:name => "Pyrenean Mastiff", :fci_number => 92)
Breed.create(:name => "Cão da Serra de Aires", :fci_number => 93)
Breed.create(:name => "Portuguese Podengo", :fci_number => 94)
Breed.create(:name => "Brittany", :fci_number => 95)
Breed.create(:name => "Rafeiro do Alentejo", :fci_number => 96)
Breed.create(:name => "German Spitz", :fci_number => 97)
Breed.create(:name => "Keeshond", :fci_number => 97)
Breed.create(:name => "Pomeranian", :fci_number => 97)
Breed.create(:name => "German Wirehaired Pointer", :fci_number => 98)
Breed.create(:name => "Weimaraner", :fci_number => 99)
Breed.create(:name => "Westphalian Dachsbracke", :fci_number => 100)
Breed.create(:name => "French Bulldog", :fci_number => 101)
Breed.create(:name => "Small Münsterländer", :fci_number => 102)
Breed.create(:name => "Jagdterrier", :fci_number => 103)
Breed.create(:name => "German Spaniel", :fci_number => 104)
Breed.create(:name => "Barbet", :fci_number => 105)
Breed.create(:name => "Épagneul Bleu de Picardie", :fci_number => 106)
Breed.create(:name => "Wirehaired Pointing Griffon", :fci_number => 107)
Breed.create(:name => "Picardy Spaniel", :fci_number => 108)
Breed.create(:name => "Clumber Spaniel", :fci_number => 109)
Breed.create(:name => "Curly Coated Retriever", :fci_number => 110)
Breed.create(:name => "Golden Retriever", :fci_number => 111)
Breed.create(:name => "Briard", :fci_number => 113)
Breed.create(:name => "Pont-Audemer Spaniel", :fci_number => 114)
Breed.create(:name => "Braque Saint-Germain", :fci_number => 115)
Breed.create(:name => "Dogue de Bordeaux", :fci_number => 116)
Breed.create(:name => "Large Münsterländer", :fci_number => 118)
Breed.create(:name => "German Shorthaired Pointer", :fci_number => 119)
Breed.create(:name => "Irish Setter", :fci_number => 120)
Breed.create(:name => "Flat-Coated Retriever", :fci_number => 121)
Breed.create(:name => "Labrador Retriever", :fci_number => 122)
Breed.create(:name => "Field Spaniel", :fci_number => 123)
Breed.create(:name => "Irish Water Spaniel", :fci_number => 124)
Breed.create(:name => "English Springer Spaniel", :fci_number => 125)
Breed.create(:name => "Welsh Springer Spaniel", :fci_number => 126)
Breed.create(:name => "Sussex Spaniel", :fci_number => 127)
Breed.create(:name => "King Charles Spaniel", :fci_number => 128)
Breed.create(:name => "Drever", :fci_number => 130)
Breed.create(:name => "Schillerstövare", :fci_number => 131)
Breed.create(:name => "Hamiltonstövare", :fci_number => 132)
Breed.create(:name => "Braque Francais", :fci_number => 133)
Breed.create(:name => "Swedish Lapphund", :fci_number => 135)
Breed.create(:name => "Cavalier King Charles Spaniel", :fci_number => 136)
Breed.create(:name => "Great Pyrenees", :fci_number => 137)
Breed.create(:name => "Irish Terrier", :fci_number => 139)
Breed.create(:name => "Boston Terrier", :fci_number => 140)
Breed.create(:name => "Pyrenean Shepherd", :fci_number => 141)
Breed.create(:name => "Slovak Cuvac", :fci_number => 142)
Breed.create(:name => "Doberman Pinscher", :fci_number => 143)
Breed.create(:name => "Boxer", :fci_number => 144)
Breed.create(:name => "Leonberger", :fci_number => 145)
Breed.create(:name => "Rhodesian Ridgeback", :fci_number => 146)
Breed.create(:name => "Rottweiler", :fci_number => 147)
Breed.create(:name => "Dachshund", :fci_number => 148)
Breed.create(:name => "Bulldog", :fci_number => 149)
Breed.create(:name => "Serbian Hound", :fci_number => 150)
Breed.create(:name => "Istrian Shorthaired Hound", :fci_number => 151)
Breed.create(:name => "Istrian Coarse-haired Hound", :fci_number => 152)
Breed.create(:name => "Dalmatian", :fci_number => 153)
Breed.create(:name => "Posavac Hound", :fci_number => 154)
Breed.create(:name => "Bosnian Coarse-haired Hound", :fci_number => 155)
Breed.create(:name => "Rough Collie", :fci_number => 156)
Breed.create(:name => "Bullmastiff", :fci_number => 157)
Breed.create(:name => "Greyhound", :fci_number => 158)
Breed.create(:name => "English Foxhound", :fci_number => 159)
Breed.create(:name => "Irish Wolfhound", :fci_number => 160)
Breed.create(:name => "Beagle", :fci_number => 161)
Breed.create(:name => "Whippet", :fci_number => 162)
Breed.create(:name => "Basset Hound", :fci_number => 163)
Breed.create(:name => "Scottish Deerhound", :fci_number => 164)
Breed.create(:name => "Spinone Italiano", :fci_number => 165)
Breed.create(:name => "German Shepherd Dog", :fci_number => 166)
Breed.create(:name => "American Cocker Spaniel", :fci_number => 167)
Breed.create(:name => "Dandie Dinmont Terrier", :fci_number => 168)
Breed.create(:name => "Wire Fox Terrier", :fci_number => 169)
Breed.create(:name => "Poodle", :fci_number => 172)
Breed.create(:name => "Estrela Mountain Dog", :fci_number => 173)
Breed.create(:name => "French Spaniel", :fci_number => 175)
Breed.create(:name => "Berger Picard", :fci_number => 176)
Breed.create(:name => "Ariege Pointer", :fci_number => 177)
Breed.create(:name => "Braque du Bourbonnais", :fci_number => 179)
Breed.create(:name => "Braque d'Auvergne", :fci_number => 180)
Breed.create(:name => "Giant Schnauzer", :fci_number => 181)
Breed.create(:name => "Giant Schnauzer", :fci_number => 181)
Breed.create(:name => "Standard Schnauzer", :fci_number => 182)
Breed.create(:name => "Miniature Schnauzer", :fci_number => 183)
Breed.create(:name => "German Pinscher", :fci_number => 184)
Breed.create(:name => "Miniature Pinscher", :fci_number => 185)
Breed.create(:name => "Affenpinscher", :fci_number => 186)
Breed.create(:name => "Portuguese Pointer", :fci_number => 187)
Breed.create(:name => "Sloughi", :fci_number => 188)
Breed.create(:name => "Finnish Lapphund", :fci_number => 189)
Breed.create(:name => "Hovawart", :fci_number => 190)
Breed.create(:name => "Bouvier des Flandres", :fci_number => 191)
Breed.create(:name => "Kromfohrländer", :fci_number => 192)
Breed.create(:name => "Borzoi", :fci_number => 193)
Breed.create(:name => "Bergamasco Shepherd", :fci_number => 194)
Breed.create(:name => "Volpino Italiano", :fci_number => 195)
Breed.create(:name => "Bolognese", :fci_number => 196)
Breed.create(:name => "Neapolitan Mastiff", :fci_number => 197)
Breed.create(:name => "Cirneco dell'Etna", :fci_number => 199)
Breed.create(:name => "Italian Greyhound", :fci_number => 200)
Breed.create(:name => "Maremma Sheepdog", :fci_number => 201)
Breed.create(:name => "Bracco Italiano", :fci_number => 202)
Breed.create(:name => "Dunker", :fci_number => 203)
Breed.create(:name => "Sabueso Español", :fci_number => 204)
Breed.create(:name => "Japanese Chin", :fci_number => 206)
Breed.create(:name => "Pekingese", :fci_number => 207)
Breed.create(:name => "Shih Tzu", :fci_number => 208)
Breed.create(:name => "Tibetan Terrier", :fci_number => 209)
Breed.create(:name => "Samoyed", :fci_number => 212)
Breed.create(:name => "Hanover Hound", :fci_number => 213)
Breed.create(:name => "Greek Harehound", :fci_number => 214)
Breed.create(:name => "Bichon Frisé", :fci_number => 215)
Breed.create(:name => "Pudelpointer", :fci_number => 216)
Breed.create(:name => "Chihuahua", :fci_number => 218)
Breed.create(:name => "Chien Français Tricolore", :fci_number => 219)
Breed.create(:name => "Chien Français Blanc et Noir", :fci_number => 220)
Breed.create(:name => "Wetterhoun", :fci_number => 221)
Breed.create(:name => "Stabyhoun", :fci_number => 222)
Breed.create(:name => "Dutch Shepherd Dog", :fci_number => 223)
Breed.create(:name => "Drentse Patrijshond", :fci_number => 224)
Breed.create(:name => "Fila Brasileiro", :fci_number => 225)
Breed.create(:name => "Landseer", :fci_number => 226)
Breed.create(:name => "Lhasa Apso", :fci_number => 227)
Breed.create(:name => "Afghan Hound", :fci_number => 228)
Breed.create(:name => "Serbian Tricolour Hound", :fci_number => 229)
Breed.create(:name => "Tibetan Mastiff", :fci_number => 230)
Breed.create(:name => "Tibetan Spaniel", :fci_number => 231)
Breed.create(:name => "Löwchen", :fci_number => 233)
Breed.create(:name => "Mexican Hairless Dog", :fci_number => 234)
Breed.create(:name => "Great Dane", :fci_number => 235)
Breed.create(:name => "Australian Silky Terrier", :fci_number => 236)
Breed.create(:name => "Norwegian Buhund", :fci_number => 237)
Breed.create(:name => "Mudi", :fci_number => 238)
Breed.create(:name => "Wirehaired Vizsla", :fci_number => 239)
Breed.create(:name => "Hungarian Hound", :fci_number => 241)
Breed.create(:name => "Norwegian Elkhound", :fci_number => 242)
Breed.create(:name => "Black Norwegian Elkhound", :fci_number => 268)
Breed.create(:name => "Alaskan Malamute", :fci_number => 243)
Breed.create(:name => "Slovenský Kopov", :fci_number => 244)
Breed.create(:name => "Cesky Fousek", :fci_number => 245)
Breed.create(:name => "Cesky Terrier", :fci_number => 246)
Breed.create(:name => "Aidi", :fci_number => 247)
Breed.create(:name => "Pharaoh Hound", :fci_number => 248)
Breed.create(:name => "Perro de Presa Mallorquin", :fci_number => 249)
Breed.create(:name => "Havanese", :fci_number => 250)
Breed.create(:name => "Polish Lowland Sheepdog", :fci_number => 251)
Breed.create(:name => "Polish Tatra Sheepdog", :fci_number => 252)
Breed.create(:name => "Pug", :fci_number => 253)
Breed.create(:name => "Alpine Dachsbracke", :fci_number => 254)
Breed.create(:name => "Akita Inu", :fci_number => 255)
Breed.create(:name => "Shiba Inu", :fci_number => 257)
Breed.create(:name => "Japanese Terrier", :fci_number => 259)
Breed.create(:name => "Tosa", :fci_number => 260)
Breed.create(:name => "Hokkaido", :fci_number => 261)
Breed.create(:name => "Japanese Spitz", :fci_number => 262)
Breed.create(:name => "Chesapeake Bay Retriever", :fci_number => 263)
Breed.create(:name => "English Mastiff", :fci_number => 264)
Breed.create(:name => "Norwegian Lundehund", :fci_number => 269)
Breed.create(:name => "Saluki", :fci_number => 269)
Breed.create(:name => "Siberian Husky", :fci_number => 270)
Breed.create(:name => "Bearded Collie", :fci_number => 271)
Breed.create(:name => "Norfolk Terrier", :fci_number => 272)
Breed.create(:name => "Canaan Dog", :fci_number => 273)
Breed.create(:name => "Greenland Dog", :fci_number => 274)
Breed.create(:name => "Norrbottenspets", :fci_number => 276)
Breed.create(:name => "Croatian Sheepdog", :fci_number => 277)
Breed.create(:name => "Karst Shepherd", :fci_number => 278)
Breed.create(:name => "Montenegrin Mountain Hound", :fci_number => 279)
Breed.create(:name => "Old Danish Pointer", :fci_number => 281)
Breed.create(:name => "Grand Griffon Vendéen", :fci_number => 282)
Breed.create(:name => "Coton de Tulear", :fci_number => 283)
Breed.create(:name => "Lapponian Herder", :fci_number => 284)
Breed.create(:name => "Galgo Español", :fci_number => 285)
Breed.create(:name => "American Staffordshire Terrier", :fci_number => 286)
Breed.create(:name => "Australian Cattle Dog", :fci_number => 287)
Breed.create(:name => "Chinese Crested Dog", :fci_number => 288)
Breed.create(:name => "Icelandic Sheepdog", :fci_number => 289)
Breed.create(:name => "Beagle-Harrier", :fci_number => 290)
Breed.create(:name => "Eurasier", :fci_number => 291)
Breed.create(:name => "Argentine Dogo", :fci_number => 292)
Breed.create(:name => "Australian Kelpie", :fci_number => 293)
Breed.create(:name => "Otterhound", :fci_number => 294)
Breed.create(:name => "Harrier", :fci_number => 295)
Breed.create(:name => "Smooth Collie", :fci_number => 296)
Breed.create(:name => "Border Collie", :fci_number => 297)
Breed.create(:name => "Lagotto Romagnolo", :fci_number => 298)
Breed.create(:name => "Black and Tan Coonhound", :fci_number => 300)
Breed.create(:name => "American Water Spaniel", :fci_number => 301)
Breed.create(:name => "Glen of Imaal Terrier", :fci_number => 302)
Breed.create(:name => "American Foxhound", :fci_number => 303)
Breed.create(:name => "Russo-European Laika", :fci_number => 304)
Breed.create(:name => "Carpathian Shepherd Dog", :fci_number => 305)
Breed.create(:name => "West Siberian Laika", :fci_number => 306)
Breed.create(:name => "Azawakh", :fci_number => 307)
Breed.create(:name => "Dutch Smoushond", :fci_number => 308)
Breed.create(:name => "Shar Pei", :fci_number => 309)
Breed.create(:name => "Peruvian Hairless Dog", :fci_number => 310)
Breed.create(:name => "Saarlooswolfhond", :fci_number => 311)
Breed.create(:name => "Nova Scotia Duck-Tolling Retriever", :fci_number => 312)
Breed.create(:name => "Schapendoes", :fci_number => 313)
Breed.create(:name => "Kooikerhondje", :fci_number => 314)
Breed.create(:name => "Broholmer", :fci_number => 315)
Breed.create(:name => "Chien Français Blanc et Orange", :fci_number => 316)
Breed.create(:name => "Kai Ken", :fci_number => 317)
Breed.create(:name => "Kishu", :fci_number => 318)
Breed.create(:name => "Shikoku", :fci_number => 319)
Breed.create(:name => "Slovakian Rough-haired Pointer", :fci_number => 320)
Breed.create(:name => "Grand Anglo-Français Blanc et Noir", :fci_number => 322)
Breed.create(:name => "Grand Anglo-Français Tricolore", :fci_number => 322)
Breed.create(:name => "Grand Anglo-Français Blanc et Orange", :fci_number => 324)
Breed.create(:name => "South Russian Ovcharka", :fci_number => 326)
Breed.create(:name => "Black Russian Terrier", :fci_number => 327)
Breed.create(:name => "Caucasian Shepherd Dog", :fci_number => 328)
Breed.create(:name => "Podenco Canario", :fci_number => 329)
Breed.create(:name => "Irish Red and White Setter", :fci_number => 330)
Breed.create(:name => "Anatolian Shepherd Dog", :fci_number => 331)
Breed.create(:name => "Czechoslovak Wolfdog", :fci_number => 332)
Breed.create(:name => "Polish Greyhound", :fci_number => 333)
Breed.create(:name => "Korean Jindo Dog", :fci_number => 334)
Breed.create(:name => "Central Asian Shepherd Dog", :fci_number => 335)
Breed.create(:name => "Spanish Water Dog", :fci_number => 336)
Breed.create(:name => "Thai Ridgeback", :fci_number => 338)
Breed.create(:name => "Parson Russell Terrier", :fci_number => 339)
Breed.create(:name => "Cão Fila de São Miguel", :fci_number => 340)
Breed.create(:name => "Brazilian Terrier", :fci_number => 341)
Breed.create(:name => "Australian Shepherd", :fci_number => 342)
Breed.create(:name => "Cane Corso", :fci_number => 343)
Breed.create(:name => "American Akita", :fci_number => 344)
Breed.create(:name => "Jack Russell Terrier", :fci_number => 345)
Breed.create(:name => "Russell Terrier", :fci_number => 345)
Breed.create(:name => "Perro de Presa Canario", :fci_number => 346)
Breed.create(:name => "Berger Blanc Suisse", :fci_number => 347)
Breed.create(:name => "Formosan Mountain Dog", :fci_number => 348)
Breed.create(:name => "Mioritic", :fci_number => 349)
Breed.create(:name => "Russian Toy", :fci_number => 352)
Breed.create(:name => "Cimarrón Uruguayo", :fci_number => 353)
Breed.create(:name => "Polish Hunting Dog", :fci_number => 354)
Breed.create(:name => "Tornjak", :fci_number => 355)
Breed.create(:name => "Appenzeller Sennenhund", :fci_number => 406)
Breed.create(:name => "Segugio Italiano", :fci_number => 0)
Breed.create(:name => "French Brittany", :fci_number => 0)
Breed.create(:name => "Bull Terrier (Miniature)", :fci_number => 0)
Breed.create(:name => "Griffon Bruxellois", :fci_number => 0)
Breed.create(:name => "Akbash Dog", :fci_number => 0)
Breed.create(:name => "Alano Español", :fci_number => 0)
Breed.create(:name => "Alapaha Blue Blood Bulldog", :fci_number => 0)
Breed.create(:name => "Alaskan Klee Kai", :fci_number => 0)
Breed.create(:name => "Alpine Spaniel", :fci_number => 0)
Breed.create(:name => "American Alsatian", :fci_number => 0)
Breed.create(:name => "American Bulldog", :fci_number => 0)
Breed.create(:name => "American Bullnese", :fci_number => 0)
Breed.create(:name => "American Bully", :fci_number => 0)
Breed.create(:name => "American Eskimo Dog", :fci_number => 0)
Breed.create(:name => "American Hairless Terrier", :fci_number => 0)
Breed.create(:name => "American Mastiff", :fci_number => 0)
Breed.create(:name => "American Pit Bull Terrier", :fci_number => 0)
Breed.create(:name => "Antebellum Bulldog", :fci_number => 0)
Breed.create(:name => "Armant", :fci_number => 0)
Breed.create(:name => "Armenian Gampr dog", :fci_number => 0)
Breed.create(:name => "Australian Bulldog", :fci_number => 0)
Breed.create(:name => "Australian Stumpy Tail Cattle Dog", :fci_number => 0)
Breed.create(:name => "Bakharwal Dog", :fci_number => 0)
Breed.create(:name => "Basque Shepherd Dog", :fci_number => 0)
Breed.create(:name => "Basset Fauve de Bretagne", :fci_number => 0)
Breed.create(:name => "Bavarian Mountain Hound", :fci_number => 0)
Breed.create(:name => "Berner Laufhund", :fci_number => 0)
Breed.create(:name => "Bisben", :fci_number => 0)
Breed.create(:name => "Black and Tan Virginia Foxhound", :fci_number => 0)
Breed.create(:name => "Blackmouth Cur", :fci_number => 0)
Breed.create(:name => "Blue Lacy", :fci_number => 0)
Breed.create(:name => "Blue Paul Terrier", :fci_number => 0)
Breed.create(:name => "Bluetick Coonhound", :fci_number => 0)
Breed.create(:name => "Boerboel", :fci_number => 0)
Breed.create(:name => "Bohemian Shepherd", :fci_number => 0)
Breed.create(:name => "Bouvier des Ardennes", :fci_number => 0)
Breed.create(:name => "Boykin Spaniel", :fci_number => 0)
Breed.create(:name => "Braque du Puy", :fci_number => 0)
Breed.create(:name => "Bruno Jura Hound", :fci_number => 0)
Breed.create(:name => "Bucovina Shepherd Dog", :fci_number => 0)
Breed.create(:name => "Bull and Terrier", :fci_number => 0)
Breed.create(:name => "Bulldog Campeiro", :fci_number => 0)
Breed.create(:name => "Bullenbeisser", :fci_number => 0)
Breed.create(:name => "Bully Kutta", :fci_number => 0)
Breed.create(:name => "Canadian Eskimo Dog", :fci_number => 0)
Breed.create(:name => "Canadian Pointer", :fci_number => 0)
Breed.create(:name => "Carolina Dog", :fci_number => 0)
Breed.create(:name => "Catahoula Cur", :fci_number => 0)
Breed.create(:name => "Chien-gris", :fci_number => 0)
Breed.create(:name => "Chilean Fox Terrier", :fci_number => 0)
Breed.create(:name => "Chinese Chongqing Dog", :fci_number => 0)
Breed.create(:name => "Chinese Imperial Dog", :fci_number => 0)
Breed.create(:name => "Chinook", :fci_number => 0)
Breed.create(:name => "Chippiparai", :fci_number => 0)
Breed.create(:name => "Chow Chow", :fci_number => 0)
Breed.create(:name => "Cierny Sery", :fci_number => 0)
Breed.create(:name => "Combai", :fci_number => 0)
Breed.create(:name => "Cordoba Fighting Dog", :fci_number => 0)
Breed.create(:name => "Cretan Hound", :fci_number => 0)
Breed.create(:name => "Cumberland Sheepdog", :fci_number => 0)
Breed.create(:name => "Cursinu", :fci_number => 0)
Breed.create(:name => "Czech Spotted dog", :fci_number => 0)
Breed.create(:name => "Danish Swedish Farmdog", :fci_number => 0)
Breed.create(:name => "Deutsche Bracke", :fci_number => 0)
Breed.create(:name => "Dogo Cubano", :fci_number => 0)
Breed.create(:name => "Dogo Guatemalteco", :fci_number => 0)
Breed.create(:name => "Dogo Sardesco", :fci_number => 0)
Breed.create(:name => "East Siberian Laika", :fci_number => 0)
Breed.create(:name => "East-European Shepherd", :fci_number => 0)
Breed.create(:name => "Elo", :fci_number => 0)
Breed.create(:name => "English Coonhound", :fci_number => 0)
Breed.create(:name => "English Shepherd", :fci_number => 0)
Breed.create(:name => "English Water Spaniel", :fci_number => 0)
Breed.create(:name => "English White Terrier", :fci_number => 0)
Breed.create(:name => "Estonian Hound", :fci_number => 0)
Breed.create(:name => "Georgian shepherd", :fci_number => 0)
Breed.create(:name => "German Longhaired Pointer", :fci_number => 0)
Breed.create(:name => "Gran Mastín de Borínquen", :fci_number => 0)
Breed.create(:name => "Grand Basset Griffon Vendéen", :fci_number => 0)
Breed.create(:name => "Gull Dong", :fci_number => 0)
Breed.create(:name => "Gull Terr", :fci_number => 0)
Breed.create(:name => "Hare Indian Dog", :fci_number => 0)
Breed.create(:name => "Hawaiian Poi Dog", :fci_number => 0)
Breed.create(:name => "Himalayan Sheepdog", :fci_number => 0)
Breed.create(:name => "Hortaya Borzaya", :fci_number => 0)
Breed.create(:name => "Hygenhund", :fci_number => 0)
Breed.create(:name => "Indian Spitz", :fci_number => 0)
Breed.create(:name => "Jonangi", :fci_number => 0)
Breed.create(:name => "Kaikadi", :fci_number => 0)
Breed.create(:name => "Kangal Dog", :fci_number => 0)
Breed.create(:name => "Kanni", :fci_number => 0)
Breed.create(:name => "Karakachan Dog", :fci_number => 0)
Breed.create(:name => "Kerry Beagle", :fci_number => 0)
Breed.create(:name => "King Shepherd", :fci_number => 0)
Breed.create(:name => "Kintamani", :fci_number => 0)
Breed.create(:name => "Koolie", :fci_number => 0)
Breed.create(:name => "Korean Mastiff", :fci_number => 0)
Breed.create(:name => "Kunming Wolfdog", :fci_number => 0)
Breed.create(:name => "Kurī", :fci_number => 0)
Breed.create(:name => "Kyi-Leo", :fci_number => 0)
Breed.create(:name => "Labrador Husky", :fci_number => 0)
Breed.create(:name => "Lancashire Heeler", :fci_number => 0)
Breed.create(:name => "Lithuanian Hound", :fci_number => 0)
Breed.create(:name => "Longhaired Whippet", :fci_number => 0)
Breed.create(:name => "Magyar Agár", :fci_number => 0)
Breed.create(:name => "McNab", :fci_number => 0)
Breed.create(:name => "Miniature Australian Shepherd", :fci_number => 0)
Breed.create(:name => "Miniature Fox Terrier", :fci_number => 0)
Breed.create(:name => "Molossus", :fci_number => 0)
Breed.create(:name => "Moscow Watchdog", :fci_number => 0)
Breed.create(:name => "Moscow Water Dog", :fci_number => 0)
Breed.create(:name => "Mountain Cur", :fci_number => 0)
Breed.create(:name => "Mountain View Cur", :fci_number => 0)
Breed.create(:name => "Mucuchies", :fci_number => 0)
Breed.create(:name => "Mudhol Hound", :fci_number => 0)
Breed.create(:name => "Murray River Curly Coated Retriever", :fci_number => 0)
Breed.create(:name => "New Zealand Huntaway", :fci_number => 0)
Breed.create(:name => "Norfolk Spaniel", :fci_number => 0)
Breed.create(:name => "North Country Beagle", :fci_number => 0)
Breed.create(:name => "Northern Inuit Dog", :fci_number => 0)
Breed.create(:name => "Old Croatian Sighthound", :fci_number => 0)
Breed.create(:name => "Old English Bulldog", :fci_number => 0)
Breed.create(:name => "Old English Terrier", :fci_number => 0)
Breed.create(:name => "Old German Shepherd Dog", :fci_number => 0)
Breed.create(:name => "Old Time Farm Shepherd", :fci_number => 0)
Breed.create(:name => "Olde English Bulldogge", :fci_number => 0)
Breed.create(:name => "Pachon Navarro", :fci_number => 0)
Breed.create(:name => "Paisley Terrier", :fci_number => 0)
Breed.create(:name => "Patterdale Terrier", :fci_number => 0)
Breed.create(:name => "Phalène", :fci_number => 0)
Breed.create(:name => "Phu Quoc ridgeback dog", :fci_number => 0)
Breed.create(:name => "Plott Hound", :fci_number => 0)
Breed.create(:name => "Pražský Krysařík", :fci_number => 0)
Breed.create(:name => "Pungsan Dog", :fci_number => 0)
Breed.create(:name => "Rajapalayam", :fci_number => 0)
Breed.create(:name => "Rampur Greyhound", :fci_number => 0)
Breed.create(:name => "Rastreador Brasileiro", :fci_number => 0)
Breed.create(:name => "Rat Terrier", :fci_number => 0)
Breed.create(:name => "Ratonero Bodeguero Andaluz", :fci_number => 0)
Breed.create(:name => "Ratonero Valenciano", :fci_number => 0)
Breed.create(:name => "Redbone Coonhound", :fci_number => 0)
Breed.create(:name => "Russian Spaniel", :fci_number => 0)
Breed.create(:name => "Saint-Usuge Spaniel", :fci_number => 0)
Breed.create(:name => "Sakhalin Husky", :fci_number => 0)
Breed.create(:name => "Sapsali", :fci_number => 0)
Breed.create(:name => "Scotch Collie", :fci_number => 0)
Breed.create(:name => "Seppala Siberian Sleddog", :fci_number => 0)
Breed.create(:name => "Shiloh Shepherd Dog", :fci_number => 0)
Breed.create(:name => "Silken Windhound", :fci_number => 0)
Breed.create(:name => "Sinhala Hound", :fci_number => 0)
Breed.create(:name => "Small Greek Domestic Dog", :fci_number => 0)
Breed.create(:name => "Smålandsstövare", :fci_number => 0)
Breed.create(:name => "Southern Hound", :fci_number => 0)
Breed.create(:name => "Sporting Lucas Terrier", :fci_number => 0)
Breed.create(:name => "St. John's Water Dog", :fci_number => 0)
Breed.create(:name => "Steinbracke", :fci_number => 0)
Breed.create(:name => "Stephens Cur", :fci_number => 0)
Breed.create(:name => "Tahltan Bear Dog", :fci_number => 0)
Breed.create(:name => "Taigan", :fci_number => 0)
Breed.create(:name => "Talbot", :fci_number => 0)
Breed.create(:name => "Tamaskan Dog", :fci_number => 0)
Breed.create(:name => "Teddy Roosevelt Terrier", :fci_number => 0)
Breed.create(:name => "Telomian", :fci_number => 0)
Breed.create(:name => "Tennessee Treeing Brindle", :fci_number => 0)
Breed.create(:name => "Tenterfield Terrier", :fci_number => 0)
Breed.create(:name => "Thai Bangkaew Dog", :fci_number => 0)
Breed.create(:name => "Toy Bulldog", :fci_number => 0)
Breed.create(:name => "Toy Fox Terrier", :fci_number => 0)
Breed.create(:name => "Toy Manchester Terrier", :fci_number => 0)
Breed.create(:name => "Toy Trawler Spaniel", :fci_number => 0)
Breed.create(:name => "Transylvanian Hound", :fci_number => 0)
Breed.create(:name => "Treeing Cur", :fci_number => 0)
Breed.create(:name => "Treeing Walker Coonhound", :fci_number => 0)
Breed.create(:name => "Trigg Hound", :fci_number => 0)
Breed.create(:name => "Tweed Water Spaniel", :fci_number => 0)
Breed.create(:name => "Utonagan", :fci_number => 0)
Breed.create(:name => "Welsh Sheepdog", :fci_number => 0)
Breed.create(:name => "White English Bulldog", :fci_number => 0)
Breed.create(:name => "White Shepherd Dog", :fci_number => 0)
